site_name: sherlock
site_description: Fun testing new packages and code
repo_url: https://github.com/mjrulesamrat/sherlock-rest
site_dir: site
copyright: Copyright &copy; 2015, <a href="https://github.com/mjrulesamrat">mjrulesamrat</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
